# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
env:
   variables:
     PROJECT: EarlyVisionAI
     DOTNET_CORE_RUNTIME: 8.0
     ENVIRONMENT: "testing"  # default environment

phases:   
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ./src/${PROJECT}/${PROJECT}.csproj # Restore only the Prism.API project
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release ./src/${PROJECT}/${PROJECT}.csproj # Build only the Prism.API project
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o ./build_output ./src/${PROJECT}/${PROJECT}.csproj --no-self-contained
      - cp Procfile ./build_output
      # Conditionally copy .ebextensions and .platform for testing environment
      - |
        if [ "$ENVIRONMENT" == "testing" ]; then
          echo "Including .ebextensions and .platform for testing environment"
          cp -r .ebextensions ./build_output/
          cp -r .platform ./build_output/
        else
          echo "Excluding .ebextensions and .platform for production environment"
        fi

artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no

reports:
  PrismAPI:
    file-format: VisualStudioTrx
    files:
      - '**/*'