version: '3.4'

services:
  earlyvisionai:
    image: ${DOCKER_REGISTRY-}earlyvisionai
    build:
      context: .
      dockerfile: src/EarlyVisionAI/Dockerfile
    environment:
      Cloudinary__ApiKey: ${Cloudinary__ApiKey}
      Cloudinary__ApiSecret: ${Cloudinary__ApiSecret}
      Gemini__ApiKey: ${Gemini__ApiKey}
      Cloudinary__Url: ${Cloudinary__Url}
